metaconf:
  ngpus:
  experiment_name: "RLS"
  ws_path: /ssd/rls-med-ws/  # Path to workspace where to save lightinig logs and other artifacts
  random_seed: 42

hyperparams:
  batch_size: 8
  lr: 0.0001
  alpha: 0.9
  b1: 0.5
  b2: 0.999
  max_epochs: 1000
  num_T: 10

dataloaders:
  train:
    tensor_dataset_name: "TensorDataset64"
    params:
      datapath: /ssd/ctln-gan-data/LIDC-IDRI
      cut_denom: 3
      cube_voxelsize: 64
      extract_size_mm: 64.0
      nodule_diameter_interval: [5.0, 30.0]
      masked: false
      mask_dilation_iters: 18
      ct_clip_range: [-1000, 600]
      mapping_range: [-0.25, 0.75]
